const fs = require('fs');
eval(fs.readFileSync('d:/Kannada Flashcards/cards.js', 'utf8').replace('window.CARDS =', 'var CARDS ='));

const inflectionsMap = {
  "ನಮಸ್ಕಾರ": { type: "noun", forms: [ {label:"singular", kannada:"ನಮಸ್ಕಾರ", translit:"namaskāra"}, {label:"plural", kannada:"ನಮಸ್ಕಾರಗಳು", translit:"namaskāragaḷu"}, {label:"genitive", kannada:"ನಮಸ್ಕಾರದ", translit:"namaskārada"}, {label:"locative", kannada:"ನಮಸ್ಕಾರದಲ್ಲಿ", translit:"namaskāradalli"}, {label:"dative", kannada:"ನಮಸ್ಕಾರಕ್ಕೆ", translit:"namaskārakke"}, {label:"ablative", kannada:"ನಮಸ್ಕಾರದಿಂದ", translit:"namaskāradinda"} ] },
  "ಧನ್ಯವಾದ": { type: "noun", forms: [ {label:"singular", kannada:"ಧನ್ಯವಾದ", translit:"dhanyavāda"}, {label:"plural", kannada:"ಧನ್ಯವಾದಗಳು", translit:"dhanyavādagaḷu"}, {label:"genitive", kannada:"ಧನ್ಯವಾದದ", translit:"dhanyavādada"}, {label:"locative", kannada:"ಧನ್ಯವಾದದಲ್ಲಿ", translit:"dhanyavādadalli"}, {label:"dative", kannada:"ಧನ್ಯವಾದಕ್ಕೆ", translit:"dhanyavādakke"}, {label:"ablative", kannada:"ಧನ್ಯವಾದದಿಂದ", translit:"dhanyavādadinda"} ] },
  "ಶುಭೋದಯ": { type: "noun", forms: [ {label:"singular", kannada:"ಶುಭೋದಯ", translit:"shubhōdaya"}, {label:"plural", kannada:"ಶುಭೋದಯಗಳು", translit:"shubhōdayagaḷu"}, {label:"genitive", kannada:"ಶುಭೋದಯದ", translit:"shubhōdayada"}, {label:"locative", kannada:"ಶುಭೋದಯದಲ್ಲಿ", translit:"shubhōdayadalli"}, {label:"dative", kannada:"ಶುಭೋದಯಕ್ಕೆ", translit:"shubhōdayakke"}, {label:"ablative", kannada:"ಶುಭೋದಯದಿಂದ", translit:"shubhōdayadinda"} ] },
  "ಹೇಗಿದ್ದೀರಾ": { type: "noun", forms: [ {label: "polite", kannada: "ಹೇಗಿದ್ದೀರಾ", translit: "hēgiddīrā"}, {label: "informal", kannada: "ಹೇಗಿದ್ದೀಯಾ", translit: "hēgiddīyā"} ] },
  "ಸ್ವಾಗತ": { type: "noun", forms: [ {label:"singular", kannada:"ಸ್ವಾಗತ", translit:"svāgata"}, {label:"plural", kannada:"ಸ್ವಾಗತಗಳು", translit:"svāgatagaḷu"}, {label:"genitive", kannada:"ಸ್ವಾಗತದ", translit:"svāgatada"}, {label:"locative", kannada:"ಸ್ವಾಗತದಲ್ಲಿ", translit:"svāgatadalli"}, {label:"dative", kannada:"ಸ್ವಾಗತಕ್ಕೆ", translit:"svāgatakke"}, {label:"ablative", kannada:"ಸ್ವಾಗತದಿಂದ", translit:"svāgatadinda"} ] },
  "ನೀರು": { type: "noun", forms: [ {label:"singular", kannada:"ನೀರು", translit:"nīru"}, {label:"plural", kannada:"ನೀರುಗಳು", translit:"nīrugaḷu"}, {label:"genitive", kannada:"ನೀರಿನ", translit:"nīrina"}, {label:"locative", kannada:"ನೀರಿನಲ್ಲಿ", translit:"nīrinalli"}, {label:"dative", kannada:"ನೀರಿಗೆ", translit:"nīrige"}, {label:"ablative", kannada:"ನೀರಿನಿಂದ", translit:"nīrininda"} ] },
  "ಊಟ": { type: "noun", forms: [ {label:"singular", kannada:"ಊಟ", translit:"ūṭa"}, {label:"plural", kannada:"ಊಟಗಳು", translit:"ūṭagaḷu"}, {label:"genitive", kannada:"ಊಟದ", translit:"ūṭada"}, {label:"locative", kannada:"ಊಟದಲ್ಲಿ", translit:"ūṭadalli"}, {label:"dative", kannada:"ಊಟಕ್ಕೆ", translit:"ūṭakke"}, {label:"ablative", kannada:"ಊಟದಿಂದ", translit:"ūṭadinda"} ] },
  "ಹಾಲು": { type: "noun", forms: [ {label:"singular", kannada:"ಹಾಲು", translit:"hālu"}, {label:"plural", kannada:"ಹಾಲುಗಳು", translit:"hālugaḷu"}, {label:"genitive", kannada:"ಹಾಲಿನ", translit:"hālina"}, {label:"locative", kannada:"ಹಾಲಿನಲ್ಲಿ", translit:"hālinalli"}, {label:"dative", kannada:"ಹಾಲಿಗೆ", translit:"hālige"}, {label:"ablative", kannada:"ಹಾಲಿನಿಂದ", translit:"hālininda"} ] },
  "ಕಾಫಿ": { type: "noun", forms: [ {label:"singular", kannada:"ಕಾಫಿ", translit:"kāfi"}, {label:"plural", kannada:"ಕಾಫಿಗಳು", translit:"kāfigaḷu"}, {label:"genitive", kannada:"ಕಾಫಿಯ", translit:"kāfiya"}, {label:"locative", kannada:"ಕಾಫಿಯಲ್ಲಿ", translit:"kāfiyalli"}, {label:"dative", kannada:"ಕಾಫಿಗೆ", translit:"kāfige"}, {label:"ablative", kannada:"ಕಾಫಿಯಿಂದ", translit:"kāfiyinda"} ] },
  "ಹಣ್ಣು": { type: "noun", forms: [ {label:"singular", kannada:"ಹಣ್ಣು", translit:"haṇṇu"}, {label:"plural", kannada:"ಹಣ್ಣುಗಳು", translit:"haṇṇugaḷu"}, {label:"genitive", kannada:"ಹಣ್ಣಿನ", translit:"haṇṇina"}, {label:"locative", kannada:"ಹಣ್ಣಿನಲ್ಲಿ", translit:"haṇṇinalli"}, {label:"dative", kannada:"ಹಣ್ಣಿಗೆ", translit:"haṇṇige"}, {label:"ablative", kannada:"ಹಣ್ಣಿನಿಂದ", translit:"haṇṇininda"} ] },
  "ಮನೆ": { type: "noun", forms: [ {label:"singular", kannada:"ಮನೆ", translit:"mane"}, {label:"plural", kannada:"ಮನೆಗಳು", translit:"manegaḷu"}, {label:"genitive", kannada:"ಮನೆಯ", translit:"maneya"}, {label:"locative", kannada:"ಮನೆಯಲ್ಲಿ", translit:"maneyalli"}, {label:"dative", kannada:"ಮನೆಗೆ", translit:"manege"}, {label:"ablative", kannada:"ಮನೆಯಿಂದ", translit:"maneyinda"} ] },
  "ಬಾಗಿಲು": { type: "noun", forms: [ {label:"singular", kannada:"ಬಾಗಿಲು", translit:"bāgilu"}, {label:"plural", kannada:"ಬಾಗಿಲುಗಳು", translit:"bāgilugaḷu"}, {label:"genitive", kannada:"ಬಾಗಿಲಿನ", translit:"bāgilina"}, {label:"locative", kannada:"ಬಾಗಿಲಿನಲ್ಲಿ", translit:"bāgilinalli"}, {label:"dative", kannada:"ಬಾಗಿಲಿಗೆ", translit:"bāgilige"}, {label:"ablative", kannada:"ಬಾಗಿಲಿನಿಂದ", translit:"bāgilininda"} ] },
  "ಕಿಟಕಿ": { type: "noun", forms: [ {label:"singular", kannada:"ಕಿಟಕಿ", translit:"kiṭaki"}, {label:"plural", kannada:"ಕಿಟಕಿಗಳು", translit:"kiṭakigaḷu"}, {label:"genitive", kannada:"ಕಿಟಕಿಯ", translit:"kiṭakiya"}, {label:"locative", kannada:"ಕಿಟಕಿಯಲ್ಲಿ", translit:"kiṭakiyalli"}, {label:"dative", kannada:"ಕಿಟಕಿಗೆ", translit:"kiṭakige"}, {label:"ablative", kannada:"ಕಿಟಕಿಯಿಂದ", translit:"kiṭakiyinda"} ] },
  "ಕುರ್ಚಿ": { type: "noun", forms: [ {label:"singular", kannada:"ಕುರ್ಚಿ", translit:"kurchi"}, {label:"plural", kannada:"ಕುರ್ಚಿಗಳು", translit:"kurchigaḷu"}, {label:"genitive", kannada:"ಕುರ್ಚಿಯ", translit:"kurchiya"}, {label:"locative", kannada:"ಕುರ್ಚಿಯಲ್ಲಿ", translit:"kurchiyalli"}, {label:"dative", kannada:"ಕುರ್ಚಿಗೆ", translit:"kurchige"}, {label:"ablative", kannada:"ಕುರ್ಚಿಯಿಂದ", translit:"kurchiyinda"} ] },
  "ಹಾಸಿಗೆ": { type: "noun", forms: [ {label:"singular", kannada:"ಹಾಸಿಗೆ", translit:"hāsige"}, {label:"plural", kannada:"ಹಾಸಿಗೆಗಳು", translit:"hāsigegaḷu"}, {label:"genitive", kannada:"ಹಾಸಿಗೆಯ", translit:"hāsigeya"}, {label:"locative", kannada:"ಹಾಸಿಗೆಯಲ್ಲಿ", translit:"hāsigeyalli"}, {label:"dative", kannada:"ಹಾಸಿಗೆಗೆ", translit:"hāsigege"}, {label:"ablative", kannada:"ಹಾಸಿಗೆಯಿಂದ", translit:"hāsigeyinda"} ] },
  "ಹೋಗು": { type: "verb", root: { kannada: "ಹೋಗು", translit: "hōgu" }, tenses: {
    present: [ {label:"I", kannada:"ಹೋಗುತ್ತೇನೆ", translit:"hōguttēne"}, {label:"you", kannada:"ಹೋಗುತ್ತೀಯಾ", translit:"hōguttīyā"}, {label:"he", kannada:"ಹೋಗುತ್ತಾನೆ", translit:"hōguttāne"}, {label:"she", kannada:"ಹೋಗುತ್ತಾಳೆ", translit:"hōguttāḷe"}, {label:"we", kannada:"ಹೋಗುತ್ತೇವೆ", translit:"hōguttēve"}, {label:"they", kannada:"ಹೋಗುತ್ತಾರೆ", translit:"hōguttāre"} ],
    past: [ {label:"I", kannada:"ಹೋದೆ", translit:"hōde"}, {label:"you", kannada:"ಹೋದೆ", translit:"hōde"}, {label:"he", kannada:"ಹೋದನು", translit:"hōdanu"}, {label:"she", kannada:"ಹೋದಳು", translit:"hōdaḷu"}, {label:"we", kannada:"ಹೋದೆವು", translit:"hōdevu"}, {label:"they", kannada:"ಹೋದರು", translit:"hōdaru"} ],
    future: [ {label:"I", kannada:"ಹೋಗುವೆನು", translit:"hōguvenu"}, {label:"you", kannada:"ಹೋಗುವೆ", translit:"hōguve"}, {label:"he", kannada:"ಹೋಗುವನು", translit:"hōguvanu"}, {label:"she", kannada:"ಹೋಗುವಳು", translit:"hōguvaḷu"}, {label:"we", kannada:"ಹೋಗುವೆವು", translit:"hōguvevu"}, {label:"they", kannada:"ಹೋಗುವರು", translit:"hōguvaru"} ]
  }, negativeForm: { kannada:"ಹೋಗುವುದಿಲ್ಲ", translit:"hōguvudilla" }, verbalNoun: { kannada:"ಹೋಗುವುದು", translit:"hōguvudu" } },
  "ಬಾ": { type: "verb", root: { kannada: "ಬಾ", translit: "bā" }, tenses: {
    present: [ {label:"I", kannada:"ಬರುತ್ತೇನೆ", translit:"baruttēne"}, {label:"you", kannada:"ಬರುತ್ತೀಯಾ", translit:"baruttīyā"}, {label:"he", kannada:"ಬರುತ್ತಾನೆ", translit:"baruttāne"}, {label:"she", kannada:"ಬರುತ್ತಾಳೆ", translit:"baruttāḷe"}, {label:"we", kannada:"ಬರುತ್ತೇವೆ", translit:"baruttēve"}, {label:"they", kannada:"ಬರುತ್ತಾರೆ", translit:"baruttāre"} ],
    past: [ {label:"I", kannada:"ಬಂದೆ", translit:"bande"}, {label:"you", kannada:"ಬಂದೆ", translit:"bande"}, {label:"he", kannada:"ಬಂದನು", translit:"bandanu"}, {label:"she", kannada:"ಬಂದಳು", translit:"bandaḷu"}, {label:"we", kannada:"ಬಂದೆವು", translit:"bandevu"}, {label:"they", kannada:"ಬಂದರು", translit:"bandaru"} ],
    future: [ {label:"I", kannada:"ಬರುವೆನು", translit:"baruvenu"}, {label:"you", kannada:"ಬರುವೆ", translit:"baruve"}, {label:"he", kannada:"ಬರುವನು", translit:"baruvanu"}, {label:"she", kannada:"ಬರುವಳು", translit:"baruvaḷu"}, {label:"we", kannada:"ಬರುವೆವು", translit:"baruvevu"}, {label:"they", kannada:"ಬರುವರು", translit:"baruvaru"} ]
  }, negativeForm: { kannada:"ಬರುವುದಿಲ್ಲ", translit:"baruvudilla" }, verbalNoun: { kannada:"ಬುವುದು", translit:"baruvudu" } },
  "ಮಾಡು": { type: "verb", root: { kannada: "ಮಾಡು", translit: "māḍu" }, tenses: {
    present: [ {label:"I", kannada:"ಮಾಡುತ್ತೇನೆ", translit:"māḍuttēne"}, {label:"you", kannada:"ಮಾಡುತ್ತೀಯಾ", translit:"māḍuttīyā"}, {label:"he", kannada:"ಮಾಡುತ್ತಾನೆ", translit:"māḍuttāne"}, {label:"she", kannada:"ಮಾಡುತ್ತಾಳೆ", translit:"māḍuttāḷe"}, {label:"we", kannada:"ಮಾಡುತ್ತೇವೆ", translit:"māḍuttēve"}, {label:"they", kannada:"ಮಾಡುತ್ತಾರೆ", translit:"māḍuttāre"} ],
    past: [ {label:"I", kannada:"ಮಾಡಿದೆ", translit:"māḍide"}, {label:"you", kannada:"ಮಾಡಿದೆ", translit:"māḍide"}, {label:"he", kannada:"ಮಾಡಿದನು", translit:"māḍidanu"}, {label:"she", kannada:"ಮಾಡಿದಳು", translit:"māḍidaḷu"}, {label:"we", kannada:"ಮಾಡಿದೆವು", translit:"māḍidevu"}, {label:"they", kannada:"ಮಾಡಿದರು", translit:"māḍidaru"} ],
    future: [ {label:"I", kannada:"ಮಾಡುವೆನು", translit:"māḍuvenu"}, {label:"you", kannada:"ಮಾಡುವೆ", translit:"māḍuve"}, {label:"he", kannada:"ಮಾಡುವನು", translit:"māḍuvanu"}, {label:"she", kannada:"ಮಾಡುವಳು", translit:"māḍuvaḷu"}, {label:"we", kannada:"ಮಾಡುವೆವು", translit:"māḍuvevu"}, {label:"they", kannada:"ಮಾಡುವರು", translit:"māḍuvaru"} ]
  }, negativeForm: { kannada:"ಮಾಡುವುದಿಲ್ಲ", translit:"māḍuvudilla" }, verbalNoun: { kannada:"ಮಾಡುವುದು", translit:"māḍuvudu" } },
  "ತಿನ್ನು": { type: "verb", root: { kannada: "ತಿನ್ನು", translit: "tinnu" }, tenses: {
    present: [ {label:"I", kannada:"ತಿನ್ನುತ್ತೇನೆ", translit:"tinnuttēne"}, {label:"you", kannada:"ತಿನ್ನುತ್ತೀಯಾ", translit:"tinnuttīyā"}, {label:"he", kannada:"ತಿನ್ನುತ್ತಾನೆ", translit:"tinnuttāne"}, {label:"she", kannada:"ತಿನ್ನುತ್ತಾಳೆ", translit:"tinnuttāḷe"}, {label:"we", kannada:"ತಿನ್ನುತ್ತೇವೆ", translit:"tinnuttēve"}, {label:"they", kannada:"ತಿನ್ನುತ್ತಾರೆ", translit:"tinnuttāre"} ],
    past: [ {label:"I", kannada:"ತಿಂದೆ", translit:"tinde"}, {label:"you", kannada:"ತಿಂದೆ", translit:"tinde"}, {label:"he", kannada:"ತಿಂದನು", translit:"tindanu"}, {label:"she", kannada:"ತಿಂದಳು", translit:"tindaḷu"}, {label:"we", kannada:"ತಿಂದೆವು", translit:"tindevu"}, {label:"they", kannada:"ತಿಂದರು", translit:"tindaru"} ],
    future: [ {label:"I", kannada:"ತಿನ್ನುವೆನು", translit:"tinnuvenu"}, {label:"you", kannada:"ತಿನ್ನುವೆ", translit:"tinnuve"}, {label:"he", kannada:"ತಿನ್ನುವನು", translit:"tinnuvanu"}, {label:"she", kannada:"ತಿನ್ನುವಳು", translit:"tinnuvaḷu"}, {label:"we", kannada:"ತಿನ್ನುವೆವು", translit:"tinnuvevu"}, {label:"they", kannada:"ತಿನ್ನುವರು", translit:"tinnuvaru"} ]
  }, negativeForm: { kannada:"ತಿನ್ನುವುದಿಲ್ಲ", translit:"tinnuvudilla" }, verbalNoun: { kannada:"ತಿನ್ನುವುದು", translit:"tinnuvudu" } },
  "ಕುಡಿ": { type: "verb", root: { kannada: "ಕುಡಿ", translit: "kuḍi" }, tenses: {
    present: [ {label:"I", kannada:"ಕುಡಿಯುತ್ತೇನೆ", translit:"kuḍiyuttēne"}, {label:"you", kannada:"ಕುಡಿಯುತ್ತೀಯಾ", translit:"kuḍiyuttīyā"}, {label:"he", kannada:"ಕುಡಿಯುತ್ತಾನೆ", translit:"kuḍiyuttāne"}, {label:"she", kannada:"ಕುಡಿಯುತ್ತಾಳೆ", translit:"kuḍiyuttāḷe"}, {label:"we", kannada:"ಕುಡಿಯುತ್ತೇವೆ", translit:"kuḍiyuttēve"}, {label:"they", kannada:"ಕುಡಿಯುತ್ತಾರೆ", translit:"kuḍiyuttāre"} ],
    past: [ {label:"I", kannada:"ಕುಡಿದೆ", translit:"kuḍide"}, {label:"you", kannada:"ಕುಡಿದೆ", translit:"kuḍide"}, {label:"he", kannada:"ಕುಡಿದನು", translit:"kuḍidanu"}, {label:"she", kannada:"ಕುಡಿದಳು", translit:"kuḍidaḷu"}, {label:"we", kannada:"ಕುಡಿದೆವು", translit:"kuḍidevu"}, {label:"they", kannada:"ಕುಡಿದರು", translit:"kuḍidaru"} ],
    future: [ {label:"I", kannada:"ಕುಡಿಯುವೆನು", translit:"kuḍiyuvenu"}, {label:"you", kannada:"ಕುಡಿಯುವೆ", translit:"kuḍiyuve"}, {label:"he", kannada:"ಕುಡಿಯುವನು", translit:"kuḍiyuvanu"}, {label:"she", kannada:"ಕುಡಿಯುವಳು", translit:"kuḍiyuvaḷu"}, {label:"we", kannada:"ಕುಡಿಯುವೆವು", translit:"kuḍiyuvevu"}, {label:"they", kannada:"ಕುಡಿಯುವರು", translit:"kuḍiyuvaru"} ]
  }, negativeForm: { kannada:"ಕುಡಿಯುವುದಿಲ್ಲ", translit:"kuḍiyuvudilla" }, verbalNoun: { kannada:"ಕುಡಿಯುವುದು", translit:"kuḍiyuvudu" } }
};

CARDS.forEach(c => {
  if (inflectionsMap[c.kannada]) {
    c.inflections = inflectionsMap[c.kannada];
  } else {
    c.inflections = { type: 'noun', forms: [{label: 'singular', kannada: c.kannada, translit: c.transliteration}] };
  }
});

fs.writeFileSync('d:/Kannada Flashcards/cards.js', 'window.CARDS = ' + JSON.stringify(CARDS, null, 2));
