// Hand-authored, JLPT-N5-appropriate example sentences, one per headword.
// Kept deliberately simple and natural so learners can actually parse them.
// Keyed by the exact word string used in wordlist.json.
module.exports = {
  // Numbers
  "一": { japanese: "リンゴを一つください。", english: "One apple, please." },
  "二": { japanese: "猫が二匹います。", english: "There are two cats." },
  "三": { japanese: "卵を三つ買いました。", english: "I bought three eggs." },
  "四": { japanese: "今、四時です。", english: "It's four o'clock now." },
  "五": { japanese: "クラスに学生が五人います。", english: "There are five students in the class." },
  "六": { japanese: "六月に日本へ行きます。", english: "I will go to Japan in June." },
  "七": { japanese: "一週間は七日です。", english: "A week has seven days." },
  "八": { japanese: "八時に起きます。", english: "I wake up at eight o'clock." },
  "九": { japanese: "九時に寝ます。", english: "I go to bed at nine o'clock." },
  "十": { japanese: "このクラスに学生が十人います。", english: "There are ten students in this class." },
  "百": { japanese: "りんごを百円で買いました。", english: "I bought an apple for 100 yen." },
  "千": { japanese: "このかばんは千円です。", english: "This bag is 1000 yen." },

  // Question words
  "何": { japanese: "これは何ですか。", english: "What is this?" },
  "誰": { japanese: "あれは誰ですか。", english: "Who is that?" },
  "どこ": { japanese: "トイレはどこですか。", english: "Where is the bathroom?" },
  "いつ": { japanese: "誕生日はいつですか。", english: "When is your birthday?" },
  "どう": { japanese: "天気はどうですか。", english: "How is the weather?" },
  "なぜ": { japanese: "なぜ遅れましたか。", english: "Why were you late?" },

  // Pronouns
  "私": { japanese: "私は学生です。", english: "I am a student." },
  "あなた": { japanese: "あなたの名前は何ですか。", english: "What is your name?" },
  "彼": { japanese: "彼は先生です。", english: "He is a teacher." },
  "彼女": { japanese: "彼女は医者です。", english: "She is a doctor." },

  // Greetings
  "こんにちは": { japanese: "こんにちは、元気ですか。", english: "Hello, how are you?" },
  "おはようございます": { japanese: "おはようございます、よく眠れましたか。", english: "Good morning, did you sleep well?" },
  "こんばんは": { japanese: "こんばんは、今日はどうでしたか。", english: "Good evening, how was your day?" },
  "ありがとう": { japanese: "手伝ってくれてありがとう。", english: "Thank you for helping me." },
  "すみません": { japanese: "すみません、今何時ですか。", english: "Excuse me, what time is it now?" },
  "さようなら": { japanese: "また明日、さようなら。", english: "See you tomorrow, goodbye." },
  "はい": { japanese: "はい、分かりました。", english: "Yes, I understand." },
  "いいえ": { japanese: "いいえ、それは違います。", english: "No, that's not right." },
  "お願いします": { japanese: "水をお願いします。", english: "Water, please." },

  // Common verbs
  "する": { japanese: "毎日、宿題をします。", english: "I do my homework every day." },
  "行く": { japanese: "明日、学校に行きます。", english: "I will go to school tomorrow." },
  "来る": { japanese: "友達が家に来ます。", english: "My friend is coming to my house." },
  "食べる": { japanese: "朝ご飯にパンを食べます。", english: "I eat bread for breakfast." },
  "飲む": { japanese: "毎朝、コーヒーを飲みます。", english: "I drink coffee every morning." },
  "見る": { japanese: "夜、テレビを見ます。", english: "I watch TV at night." },
  "話す": { japanese: "友達と日本語で話します。", english: "I talk with my friend in Japanese." },
  "聞く": { japanese: "音楽を聞くのが好きです。", english: "I like listening to music." },
  "寝る": { japanese: "毎晩十時に寝ます。", english: "I go to sleep at ten every night." },
  "起きる": { japanese: "朝六時に起きます。", english: "I wake up at six in the morning." },
  "読む": { japanese: "図書館で本を読みます。", english: "I read a book at the library." },
  "書く": { japanese: "手紙を書いています。", english: "I am writing a letter." },
  "買う": { japanese: "スーパーで果物を買います。", english: "I buy fruit at the supermarket." },
  "会う": { japanese: "明日、友達に会います。", english: "I will meet my friend tomorrow." },
  "待つ": { japanese: "駅で友達を待っています。", english: "I am waiting for my friend at the station." },
  "立つ": { japanese: "バスの中でずっと立っていました。", english: "I was standing the whole time on the bus." },
  "座る": { japanese: "どうぞ、こちらに座ってください。", english: "Please, sit here." },
  "分かる": { japanese: "この問題が分かりません。", english: "I don't understand this problem." },
  "帰る": { japanese: "六時に家に帰ります。", english: "I will go home at six o'clock." },
  "泳ぐ": { japanese: "夏は海で泳ぎます。", english: "In summer, I swim in the sea." },
  "遊ぶ": { japanese: "子供たちは公園で遊びます。", english: "The children play in the park." },
  "死ぬ": { japanese: "魚は水がないと死んでしまいます。", english: "Fish will die without water." },
  "呼ぶ": { japanese: "タクシーを呼びましょう。", english: "Let's call a taxi." },
  "乗る": { japanese: "毎日、電車に乗ります。", english: "I ride the train every day." },
  "降りる": { japanese: "次の駅で降ります。", english: "I will get off at the next station." },
  "開ける": { japanese: "窓を開けてもいいですか。", english: "May I open the window?" },
  "閉める": { japanese: "ドアを閉めてください。", english: "Please close the door." },
  "教える": { japanese: "先生は日本語を教えています。", english: "The teacher teaches Japanese." },
  "覚える": { japanese: "新しい単語を覚えます。", english: "I memorize new words." },
  "忘れる": { japanese: "傘を忘れないでください。", english: "Please don't forget your umbrella." },

  // Family & people
  "お母さん": { japanese: "私のお母さんは料理が上手です。", english: "My mother is good at cooking." },
  "お父さん": { japanese: "お父さんは会社で働いています。", english: "My father works at a company." },
  "男": { japanese: "あの男は誰ですか。", english: "Who is that man?" },
  "女": { japanese: "この女の人は先生です。", english: "This woman is a teacher." },
  "子供": { japanese: "公園で子供が遊んでいます。", english: "Children are playing in the park." },
  "人": { japanese: "この町にはたくさんの人がいます。", english: "There are many people in this town." },
  "友達": { japanese: "友達と映画を見ました。", english: "I watched a movie with my friend." },
  "兄": { japanese: "兄はサッカーが上手です。", english: "My older brother is good at soccer." },
  "弟": { japanese: "弟はまだ小学生です。", english: "My younger brother is still in elementary school." },
  "姉": { japanese: "姉は東京で働いています。", english: "My older sister works in Tokyo." },
  "妹": { japanese: "妹はピアノを習っています。", english: "My younger sister is learning piano." },
  "家族": { japanese: "私の家族は五人です。", english: "There are five people in my family." },
  "両親": { japanese: "両親は大阪に住んでいます。", english: "My parents live in Osaka." },
  "祖父": { japanese: "祖父は毎朝散歩します。", english: "My grandfather takes a walk every morning." },
  "祖母": { japanese: "祖母はお菓子を作るのが得意です。", english: "My grandmother is good at making sweets." },
  "男の子": { japanese: "あの男の子は元気ですね。", english: "That boy is energetic, isn't he." },
  "女の子": { japanese: "あの女の子はかわいいです。", english: "That girl is cute." },
  "大人": { japanese: "このチケットは大人二枚ください。", english: "Two adult tickets, please." },
  "先生": { japanese: "先生に質問しました。", english: "I asked the teacher a question." },
  "学生": { japanese: "私は大学の学生です。", english: "I am a university student." },
  "医者": { japanese: "医者に相談しました。", english: "I consulted a doctor." },
  "警察官": { japanese: "警察官に道を聞きました。", english: "I asked a police officer for directions." },

  // Time & days
  "今日": { japanese: "今日はいい天気です。", english: "Today is nice weather." },
  "明日": { japanese: "明日は休みです。", english: "Tomorrow is a day off." },
  "今": { japanese: "今、何をしていますか。", english: "What are you doing now?" },
  "時間": { japanese: "時間がありません。急ぎましょう。", english: "There's no time. Let's hurry." },
  "時計": { japanese: "この時計はとても正確です。", english: "This clock is very accurate." },
  "朝": { japanese: "朝は静かです。", english: "Mornings are quiet." },
  "昼": { japanese: "昼にラーメンを食べました。", english: "I ate ramen at noon." },
  "夜": { japanese: "夜、星がきれいです。", english: "The stars are beautiful at night." },
  "昨日": { japanese: "昨日は雨でした。", english: "It rained yesterday." },
  "毎日": { japanese: "毎日、日本語を勉強します。", english: "I study Japanese every day." },
  "毎週": { japanese: "毎週、映画を見に行きます。", english: "I go to watch a movie every week." },
  "毎月": { japanese: "毎月、本を三冊読みます。", english: "I read three books every month." },
  "毎年": { japanese: "毎年、夏に旅行します。", english: "I travel every summer." },
  "月曜日": { japanese: "月曜日から仕事が始まります。", english: "Work starts on Monday." },
  "火曜日": { japanese: "火曜日にテストがあります。", english: "There is a test on Tuesday." },
  "水曜日": { japanese: "水曜日は休みです。", english: "Wednesday is a day off." },
  "木曜日": { japanese: "木曜日に友達に会います。", english: "I will meet my friend on Thursday." },
  "金曜日": { japanese: "金曜日の夜はいつも楽しいです。", english: "Friday nights are always fun." },
  "土曜日": { japanese: "土曜日に買い物に行きます。", english: "I go shopping on Saturday." },
  "日曜日": { japanese: "日曜日は家族と過ごします。", english: "I spend Sunday with my family." },
  "週": { japanese: "来週、旅行に行きます。", english: "I will go on a trip next week." },
  "月": { japanese: "来月、誕生日です。", english: "My birthday is next month." },
  "年": { japanese: "今年は忙しいです。", english: "This year is busy." },
  "春": { japanese: "春は桜がきれいです。", english: "The cherry blossoms are beautiful in spring." },
  "夏": { japanese: "夏はとても暑いです。", english: "Summer is very hot." },
  "秋": { japanese: "秋は食べ物がおいしいです。", english: "Food is delicious in autumn." },
  "冬": { japanese: "冬は雪が降ります。", english: "It snows in winter." },

  // Food & drink
  "水": { japanese: "水を一杯ください。", english: "Please give me a glass of water." },
  "お茶": { japanese: "食後にお茶を飲みます。", english: "I drink tea after meals." },
  "コーヒー": { japanese: "朝はいつもコーヒーを飲みます。", english: "I always drink coffee in the morning." },
  "牛乳": { japanese: "子供は牛乳が好きです。", english: "Children like milk." },
  "ご飯": { japanese: "もうご飯を食べましたか。", english: "Have you eaten yet?" },
  "パン": { japanese: "このパンはとてもおいしいです。", english: "This bread is very delicious." },
  "肉": { japanese: "肉と魚、どちらが好きですか。", english: "Which do you like more, meat or fish?" },
  "魚": { japanese: "魚は健康にいいです。", english: "Fish is good for your health." },
  "卵": { japanese: "朝ご飯に卵を食べます。", english: "I eat eggs for breakfast." },
  "野菜": { japanese: "野菜をたくさん食べましょう。", english: "Let's eat plenty of vegetables." },
  "果物": { japanese: "好きな果物は何ですか。", english: "What's your favorite fruit?" },
  "りんご": { japanese: "りんごを一つ食べました。", english: "I ate an apple." },
  "みかん": { japanese: "冬にみかんをよく食べます。", english: "I often eat mandarin oranges in winter." },
  "お菓子": { japanese: "お菓子を食べすぎないでください。", english: "Please don't eat too many sweets." },
  "塩": { japanese: "スープに塩を入れます。", english: "I add salt to the soup." },
  "砂糖": { japanese: "コーヒーに砂糖を入れますか。", english: "Do you put sugar in your coffee?" },
  "醤油": { japanese: "お寿司に醤油をつけます。", english: "I dip sushi in soy sauce." },
  "朝ご飯": { japanese: "朝ご飯を食べる時間がありません。", english: "I don't have time to eat breakfast." },
  "昼ご飯": { japanese: "友達と昼ご飯を食べました。", english: "I ate lunch with my friend." },
  "晩ご飯": { japanese: "今日の晩ご飯は何ですか。", english: "What's for dinner today?" },
  "食堂": { japanese: "学校の食堂でご飯を食べます。", english: "I eat at the school cafeteria." },
  "レストラン": { japanese: "誕生日にレストランへ行きました。", english: "We went to a restaurant for my birthday." },

  // Animals & nature
  "犬": { japanese: "公園で犬と散歩しました。", english: "I took a walk with my dog in the park." },
  "猫": { japanese: "うちの猫はよく寝ます。", english: "My cat sleeps a lot." },
  "鳥": { japanese: "木の上に鳥がいます。", english: "There is a bird on top of the tree." },
  "牛": { japanese: "牧場にたくさんの牛がいます。", english: "There are many cows on the farm." },
  "馬": { japanese: "馬はとても速く走ります。", english: "Horses run very fast." },
  "豚": { japanese: "豚肉は日本料理でよく使われます。", english: "Pork is often used in Japanese cooking." },
  "動物": { japanese: "動物園で色々な動物を見ました。", english: "I saw various animals at the zoo." },
  "木": { japanese: "庭に大きい木があります。", english: "There is a big tree in the garden." },
  "花": { japanese: "春にきれいな花が咲きます。", english: "Beautiful flowers bloom in spring." },
  "山": { japanese: "週末に山に登ります。", english: "I will climb a mountain this weekend." },
  "川": { japanese: "この川はとてもきれいです。", english: "This river is very clean." },
  "空": { japanese: "今日は空が青いです。", english: "The sky is blue today." },
  "海": { japanese: "夏に海へ行きたいです。", english: "I want to go to the sea in summer." },
  "太陽": { japanese: "太陽が東から昇ります。", english: "The sun rises in the east." },
  "星": { japanese: "夜空にたくさんの星が見えます。", english: "You can see many stars in the night sky." },
  "雨": { japanese: "明日は雨が降るでしょう。", english: "It will probably rain tomorrow." },
  "雪": { japanese: "冬に雪がたくさん降ります。", english: "A lot of snow falls in winter." },
  "風": { japanese: "今日は風が強いです。", english: "The wind is strong today." },

  // Places & transportation
  "家": { japanese: "今日は家でゆっくりします。", english: "I will relax at home today." },
  "学校": { japanese: "学校まで歩いて行きます。", english: "I walk to school." },
  "会社": { japanese: "父は毎日会社に行きます。", english: "My father goes to the company every day." },
  "病院": { japanese: "病院で薬をもらいました。", english: "I got medicine at the hospital." },
  "銀行": { japanese: "銀行でお金をおろします。", english: "I withdraw money at the bank." },
  "郵便局": { japanese: "郵便局で切手を買いました。", english: "I bought stamps at the post office." },
  "店": { japanese: "あの店は安くていいです。", english: "That shop is cheap and good." },
  "駅": { japanese: "駅の前で待っています。", english: "I am waiting in front of the station." },
  "道": { japanese: "この道をまっすぐ行ってください。", english: "Please go straight on this road." },
  "公園": { japanese: "公園で花見をしました。", english: "We had flower viewing in the park." },
  "映画館": { japanese: "週末に映画館へ行きます。", english: "I will go to the movie theater this weekend." },
  "図書館": { japanese: "図書館で静かに勉強します。", english: "I study quietly at the library." },
  "町": { japanese: "この町は小さいですが有名です。", english: "This town is small but famous." },
  "国": { japanese: "あなたの国はどこですか。", english: "Which country are you from?" },
  "外国": { japanese: "外国で働きたいです。", english: "I want to work abroad." },
  "車": { japanese: "車で会社に行きます。", english: "I go to the company by car." },
  "電車": { japanese: "電車で学校に通っています。", english: "I commute to school by train." },
  "自転車": { japanese: "自転車で駅まで行きます。", english: "I go to the station by bicycle." },
  "飛行機": { japanese: "飛行機で日本へ行きます。", english: "I will go to Japan by airplane." },
  "バス": { japanese: "バスに乗って会社に行きます。", english: "I go to work by bus." },
  "タクシー": { japanese: "雨の日はタクシーを使います。", english: "I use a taxi on rainy days." },
  "船": { japanese: "船で島へ行きました。", english: "I went to the island by boat." },
  "地下鉄": { japanese: "地下鉄はとても便利です。", english: "The subway is very convenient." },

  // Adjectives
  "大きい": { japanese: "この家はとても大きいです。", english: "This house is very big." },
  "小さい": { japanese: "私の部屋は小さいです。", english: "My room is small." },
  "新しい": { japanese: "新しい靴を買いました。", english: "I bought new shoes." },
  "古い": { japanese: "この本はとても古いです。", english: "This book is very old." },
  "良い": { japanese: "天気がとても良いです。", english: "The weather is very good." },
  "悪い": { japanese: "気分が悪いです。", english: "I feel unwell." },
  "暑い": { japanese: "今日はとても暑いです。", english: "It is very hot today." },
  "寒い": { japanese: "冬は寒いです。", english: "Winter is cold." },
  "熱い": { japanese: "このコーヒーはとても熱いです。", english: "This coffee is very hot." },
  "冷たい": { japanese: "冷たい水が飲みたいです。", english: "I want to drink cold water." },
  "高い": { japanese: "このかばんは高いです。", english: "This bag is expensive." },
  "安い": { japanese: "この店は安くて便利です。", english: "This shop is cheap and convenient." },
  "低い": { japanese: "あの山は低いです。", english: "That mountain is low." },
  "広い": { japanese: "この公園はとても広いです。", english: "This park is very spacious." },
  "狭い": { japanese: "私の部屋は狭いです。", english: "My room is narrow." },
  "難しい": { japanese: "この問題は難しいです。", english: "This problem is difficult." },
  "易しい": { japanese: "このテストは易しいです。", english: "This test is easy." },
  "美味しい": { japanese: "このラーメンはとても美味しいです。", english: "This ramen is very delicious." },
  "まずい": { japanese: "このスープはまずいです。", english: "This soup tastes bad." },
  "忙しい": { japanese: "今週はとても忙しいです。", english: "I am very busy this week." },
  "楽しい": { japanese: "旅行はとても楽しかったです。", english: "The trip was very fun." },
  "面白い": { japanese: "この映画は面白いです。", english: "This movie is interesting." },
  "つまらない": { japanese: "この授業はつまらないです。", english: "This class is boring." },
  "近い": { japanese: "学校は駅から近いです。", english: "The school is close to the station." },
  "遠い": { japanese: "家から会社まで遠いです。", english: "It's far from home to the company." },
  "速い": { japanese: "新幹線はとても速いです。", english: "The shinkansen is very fast." },
  "遅い": { japanese: "バスが遅いです。", english: "The bus is late." },
  "重い": { japanese: "このかばんは重いです。", english: "This bag is heavy." },
  "軽い": { japanese: "このノートパソコンは軽いです。", english: "This laptop is light." }
};
